# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uBlaze/uBlaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze || ORIG_REF_NAME==uBlaze} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_axi_uartlite_0_0/uBlaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==uBlaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_clk_wiz_0_0/uBlaze_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_clk_wiz_0_0 || ORIG_REF_NAME==uBlaze_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_mdm_1_0/uBlaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_mdm_1_0 || ORIG_REF_NAME==uBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_microblaze_0_0/uBlaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_microblaze_0_0 || ORIG_REF_NAME==uBlaze_microblaze_0_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_microblaze_0_axi_periph_0/uBlaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_rst_clk_wiz_0_100M_0/uBlaze_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uBlaze_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_dlmb_bram_if_cntlr_0/uBlaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_dlmb_v10_0/uBlaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_dlmb_v10_0 || ORIG_REF_NAME==uBlaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_ilmb_bram_if_cntlr_0/uBlaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_ilmb_v10_0/uBlaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_ilmb_v10_0 || ORIG_REF_NAME==uBlaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_lmb_bram_0/uBlaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_lmb_bram_0 || ORIG_REF_NAME==uBlaze_lmb_bram_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_xbar_0/uBlaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_xbar_0 || ORIG_REF_NAME==uBlaze_xbar_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_axi_gpio_0_0/uBlaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_axi_gpio_0_0 || ORIG_REF_NAME==uBlaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_axi_gpio_1_1/uBlaze_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_axi_gpio_1_1 || ORIG_REF_NAME==uBlaze_axi_gpio_1_1} -quiet] -quiet

# IP: bd/uBlaze/ip/uBlaze_PmodACL2_0_0/uBlaze_PmodACL2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_PmodACL2_0_0 || ORIG_REF_NAME==uBlaze_PmodACL2_0_0} -quiet] -quiet

# XDC: bd/uBlaze/uBlaze_ooc.xdc
